In [153]:
import numpy as np
import copy

In [154]:
x = np.array(range(12))
print(x)
x = x.reshape(3,4)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [155]:
for i in range(3):
    for j in range(3):
        print(x[i,j])
    

0
1
2
4
5
6
8
9
10


In [156]:
print(x[0,2])

2


In [157]:
print(x.shape)

(3, 4)


## Function to swap

In [158]:
def swap(pos_1_row, pos_1_col, pos_2_row, pos_2_col, state):
    '''
    This function swaps the contents of the state given source(empty place) and destination
    
    @params - 
            pos_1_row -> row index of empty place
            pos_1_col -> col index of empty place
            pos_2_row -> row index of place to be swapped with empty place
            pos_2_col -> col index of place to be swapped with empty place
            state -> the state where the swap is to be made
            
    @return - 
            new_state -> new state with the source and destination swapped
    '''
    
    #create new state
    new_state = copy.deepcopy(state)
    # print(new_state) # debug

    # make the swap with empty in the new state 
    new_state[pos_1_row, pos_1_col] = new_state[pos_1_row, pos_1_col] + new_state[pos_2_row, pos_2_col]
    new_state[pos_2_row, pos_2_col] = new_state[pos_1_row, pos_1_col] - new_state[pos_2_row, pos_2_col]
    new_state[pos_1_row, pos_1_col] = new_state[pos_1_row, pos_1_col] - new_state[pos_2_row, pos_2_col]
    
    return new_state
    
    

#### Test swap()

Our test array

In [159]:
x = np.array(range(12))
x = x.reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Lets try to swap 0 with 5 

In [160]:
# our indices
pos_1_row = 0
pos_1_col = 0
pos_2_row = 1
pos_2_col = 1

# swap
new_state = swap(pos_1_row, pos_1_col, pos_2_row, pos_2_col, x)
print(new_state)

[[ 5  1  2  3]
 [ 4  0  6  7]
 [ 8  9 10 11]]


Lets try one more swap

In [161]:
y = copy.deepcopy(x)
y[2,2] = 0
y[0,0] = 10
print(y)

[[10  1  2  3]
 [ 4  5  6  7]
 [ 8  9  0 11]]


Lets swap 7 with 0

In [162]:
# our indices
pos_1_row = 2
pos_1_col = 2
pos_2_row = 1
pos_2_col = 3

# swap
new_state = swap(pos_1_row, pos_1_col, pos_2_row, pos_2_col, y)
print(new_state)

[[10  1  2  3]
 [ 4  5  6  0]
 [ 8  9  7 11]]


## Function to find possible states

#### Rule to break ties
#### UP > UP –RIGHT > RIGHT > DOWN- RIGHT > DOWN > DOWN –LEFT > LEFT > UP–LEFT

In [163]:
# return a list of possible moves
def possible_moves(curr_state):
    '''
    This function calulates all the possible child states given a state
    @params -
            curr_state -> The parent state
    @return -
            possible_states -> A list of possible moves
    
    '''
    '''
    UP > UP –RIGHT > RIGHT > DOWN- RIGHT > DOWN > DOWN –LEFT > LEFT > UP–LEFT
    (most preferred moves)                            (least preferred moves)
    '''
    
    '''
    [i,j]- i is row, j is column
    possible moves is 8 
    
    [i-1, j]-> move up
    [i-1, j+1]-> move up-right
    [i, j+1]-> move right
    [i+1, j+1]-> move down-right
    [i+1, j]-> move down
    [i+1, j-1]-> move down-left
    [i, j-1]-> move left
    [i-1, j-1]-> move up-left
    '''
    index_moves = [[-1,0], [-1,1], [0,1], [1,1], [1,0], [1,-1], [0,-1], [-1,-1]]
    index_move_dir = ["up","up-right","right","down-right","down","down-left","left","up-left"]
    possible_states = []
    
    
    # find empty space
    empty_space = np.where(curr_state == 0)
    row_empty = int(empty_space[0])
    col_empty = int(empty_space[1])
    
    #note numpy shape gives 1-indexed row and column
    row = curr_state.shape[0] - 1
    col = curr_state.shape[1] - 1
    
    empty_space = [row_empty, col_empty]
    
    for i in range(len(index_moves)):
        pos_2_row = row_empty + index_moves[i][0]
        pos_2_col = col_empty + index_moves[i][1]
        # check for invalid moves
        if(pos_2_row<0 or pos_2_row>row or pos_2_col<0 or pos_2_col>col):
            continue
        state = copy.deepcopy(curr_state)
        possible_states.append([swap(row_empty, col_empty, pos_2_row, pos_2_col, state),index_move_dir[i]])
        
    return possible_states
    
    

#### Test possible_moves()

In [164]:
print(x)
print()
print("------------------MOVES------------------")
possible_states = possible_moves(x)
for i in possible_states:
    print(i[0], i[1])
    print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

------------------MOVES------------------
[[ 1  0  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] right

[[ 5  1  2  3]
 [ 4  0  6  7]
 [ 8  9 10 11]] down-right

[[ 4  1  2  3]
 [ 0  5  6  7]
 [ 8  9 10 11]] down



In [165]:
print(y)
print()
print("------------------MOVES------------------")
possible_states = possible_moves(y)
for i in possible_states:
    print(i[0], i[1])
    print()

[[10  1  2  3]
 [ 4  5  6  7]
 [ 8  9  0 11]]

------------------MOVES------------------
[[10  1  2  3]
 [ 4  5  0  7]
 [ 8  9  6 11]] up

[[10  1  2  3]
 [ 4  5  6  0]
 [ 8  9  7 11]] up-right

[[10  1  2  3]
 [ 4  5  6  7]
 [ 8  9 11  0]] right

[[10  1  2  3]
 [ 4  5  6  7]
 [ 8  0  9 11]] left

[[10  1  2  3]
 [ 4  0  6  7]
 [ 8  9  5 11]] up-left



## Heuristic ***(Simple Manhattan Distance)***

In [166]:
def manhattan_h(curr_state, goal_state):
    '''
    This function calculates the distance between current state and goal by calculating the sum of manhattan distance
    between two misplaced tiles.
    
    @params - 
        curr_state -> The current state
        goal_state -> The goal state
    @return -
        tot_distance -> The distance between two states
    '''
    #note numpy shape gives 1-indexed row and column
    row = curr_state.shape[0]
    col = curr_state.shape[1]
    
    tot_dist = 0
    for i in range(row*col):
        curr_pos_i = np.where(curr_state == i)
        goal_pos_i = np.where(goal_state == i)
        manhattan_dist = abs(curr_pos_i[0] - goal_pos_i[0]) + abs(curr_pos_i[1] - goal_pos_i[1])
        tot_dist = int(manhattan_dist) + tot_dist

    return tot_dist
        
        

#### Test manhattan_h()

In [167]:
print(manhattan_h(y,x)) #should print 8

8


## Best First Search

In [290]:
def best_first_search(curr_state, goal_state, heuristic):
    
    # to be searched priority queue [start by putting starting state here]
    # movement priority
    index_move_priority = ["up","up-right","right","down-right","down","down-left","left","up-left"]
    
    # our priority queue
    open_nodes = {}
    
    # explored nodes
    explored_nodes = []
    
    # put current state in queue
    open_nodes.setdefault(heuristic(curr_state, goal_state), [[curr_state,"up"]])
    print("BLYAT",open_nodes)
    # while open_nodes is not empty
    GOAL_FOUND = False
    count = 0
    print(">>>>>>>>>>>>>>>",list(open_nodes.values()))
    while(not not open_nodes):
#         print(open_nodes)
        # using dictionary as priority queue since our keys are heuristic values[int] 
        count = count + 1
        
#         if count>4:
            
#             return (explored_list, GOAL_FOUND)
        keylist = list(open_nodes.keys()) # Note python uses hash to generate hash for dictionary
                                    # Since map(hash,[0,1,2,3]) gives [0,1,2,3]) 
                                    # https://www.laurentluce.com/posts/python-dictionary-implementation/
        
        # get next node from priority queue
        find_neighbor_node = None
        temp = False
        for move in index_move_priority:
            for item in open_nodes[keylist[0]]: # item in list of states
                if move == item[1]:
                    print("KLYST",keylist[0])
                    print("////////////////",open_nodes[keylist[0]])
                    print("ITEM->",item)
                    print(type(open_nodes[keylist[0]]))
                    print(type(item))
                    open_nodes[keylist[0]].remove(item)
                    find_neighbor_node = item
                    temp = True
                    break
            if temp == True:
                break
        print("find_neighbor", find_neighbor_node)           
        # add the node to explored list
        explored_nodes.append(find_neighbor_node)
        
        # find neighbors
        neighbors = possible_moves(find_neighbor_node[0])
#         print(neighbors)
        # apply heuristic to each neighbor and put it to priority queue iff it is not in explored_list or open_node
        open_list = [] #expensive operation
#         print(">>>>>>>>>>>>>>>",list(open_nodes.values()))
        for list_of_list in list(open_nodes.values()):
#             print("HHH",list_of_list)
            for sub_list in list_of_list:
                for sub_sub_list in sub_list:
                    if type(sub_sub_list) == str:
                        continue
                    open_list.append(sub_sub_list.tolist())
                
        
        explored_list = []
        
        for sub_list in explored_nodes:
            explored_list.append(sub_list[0].tolist())
        
        print("OPEN",open_list)
        print("EXP_LIST",explored_list)
        # iterate over neighbor
        count_2 = 0
        for neighbor in neighbors:
#             print(neighbor)
            # if neighbor is goal state return solution
            if np.array_equal(neighbor[0], goal_state):
                GOAL_FOUND = True
                explored_nodes.append(neighbor)
                break
            count_2 = count_2 + 1
            print(count_2)
            # check if nieghbor is already in open_node or explored_list. If present then skip loop
            print("HERE ", neighbor[0],  end="", flush=True)
#             print(explored_list)
            temp = neighbor[0].tolist()
            if temp in explored_list or temp in open_list:
                continue
            
            # calculate the heuristic and put in priority queue open_nodes
            h = heuristic(neighbor[0],goal_state)
            print(h)
            open_nodes.setdefault(h,[]).append(neighbor)
        print("OPEN_NODES",open_nodes)
            
        if GOAL_FOUND == True:
            return (explored_nodes, GOAL_FOUND)
    
    return (explored_nodes, GOAL_FOUND)
    
    

In [291]:
a, b = best_first_search(y, x, manhattan_h)
for moves in a:
    print(moves[0],moves[1])

BLYAT {8: [[array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  0, 11]]), 'up']]}
>>>>>>>>>>>>>>> [[[array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  0, 11]]), 'up']]]
KLYST 8
//////////////// [[array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  0, 11]]), 'up']]
ITEM-> [array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  0, 11]]), 'up']
<class 'list'>
<class 'list'>
find_neighbor [array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  0, 11]]), 'up']
OPEN []
EXP_LIST [[[10, 1, 2, 3], [4, 5, 6, 7], [8, 9, 0, 11]]]
1
HERE  [[10  1  2  3]
 [ 4  5  0  7]
 [ 8  9  6 11]]8
2
HERE  [[10  1  2  3]
 [ 4  5  6  0]
 [ 8  9  7 11]]10
3
HERE  [[10  1  2  3]
 [ 4  5  6  7]
 [ 8  9 11  0]]10
4
HERE  [[10  1  2  3]
 [ 4  5  6  7]
 [ 8  0  9 11]]8
5
HERE  [[10  1  2  3]
 [ 4  0  6  7]
 [ 8  9  5 11]]8
OPEN_NODES {8: [[array([[10,  1,  2,  3],
       [ 4,  5,  0,  7],
       [ 8,  9,  6, 11]]), 'up'], [array([[10,  1,  2,  3],
 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [21]:
x = [1,2]
z = [[-1,0],[1,0],[0,-1],[0,+1],[-1,-1],[1,1],[1,-1],[-1,1]]
for item in z:
    item = item + x
    print(item)


[-1, 0, 1, 2]
[1, 0, 1, 2]
[0, -1, 1, 2]
[0, 1, 1, 2]
[-1, -1, 1, 2]
[1, 1, 1, 2]
[1, -1, 1, 2]
[-1, 1, 1, 2]


In [72]:
print(tuple([1,2]))

(1, 2)


In [277]:
dic = {}
dic.setdefault(1,[]).append(12)
dic[2]=1
dic.setdefault(1,[]).append(34)
dic[1].append(2)
dic[3]="dadsdsd"
print(dic)
klst = list(dic.keys())
# print(klst)
print(dic[1])
for item in dic[klst[0]]:
    if item == 2:
        dic[klst[0]].remove(item)
        print(item)
        break
        
print(dic)
# print(list(dic.values()))
# print(dic[2])

{1: [12, 34, 2], 2: 1, 3: 'dadsdsd'}
[12, 34, 2]
2
{1: [12, 34], 2: 1, 3: 'dadsdsd'}


In [105]:
print(list(map(hash, [0,0.2,0.9, 1, 2, 3])))


[0, 461168601842738816, 2075258708292324608, 1, 2, 3]


In [247]:
d = []
if d == []:
    print("abba dabba jabba")
for j in d:
    if j == None:
        print("Booya!")

abba dabba jabba


In [255]:
a = "abcd"
if type(a) == str:
    print("a")

a


In [262]:
lst = [1,2,3,4,5,67,7]
lst.remove(3)
print(lst)

[1, 2, 4, 5, 67, 7]


In [295]:
dic = {1:[[[1],2],[[2],3],[[3],4]],2:[[[5],6],[[7],8]],3:[[[9],10],[[11],12]]}
klst = list(dic.keys())
# print(klst)
print(dic[1])
for item in dic[klst[0]]:
    if item == [[2],3]:
        dic[klst[0]].remove(item)
        print(item)
        break
        
print(dic)


[[[1], 2], [[2], 3], [[3], 4]]
[[2], 3]
{1: [[[1], 2], [[3], 4]], 2: [[[5], 6], [[7], 8]], 3: [[[9], 10], [[11], 12]]}


In [296]:
alist = [np.array([1,2]),np.array([3,4])]
alist.remove(np.array([1,2]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()